const UA = 'Mozilla/5.0 (compatible; TVRI-LayananPublik/1.0; +https://tvri.go.id/)';

function safeText(s='') {
  return String(s).replace(/[<>&"']/g, c => ({'<':'&lt;','>':'&gt;','&':'&amp;','"':'&quot;',"'":'&#39;'}[c]));
}

function initials(name='RI') {
  const words = String(name)
    .replace(/Kementerian|Republik Indonesia|Badan|Direktorat|Portal|Layanan|Komisi|Nasional/gi, ' ')
    .trim().split(/\s+/).filter(Boolean);
  return (words.slice(0,2).map(w => w[0]).join('').toUpperCase() || 'RI').slice(0,3);
}

function svgFallback(name) {
  const t = safeText(initials(name));
  return `<svg xmlns="http://www.w3.org/2000/svg" width="128" height="128" viewBox="0 0 128 128"><rect width="128" height="128" rx="24" fill="#eaf4ff"/><circle cx="64" cy="64" r="45" fill="#0c5da5"/><text x="64" y="73" text-anchor="middle" font-family="Arial,Helvetica,sans-serif" font-size="31" font-weight="700" fill="#fff">${t}</text></svg>`;
}

function json(data, status=200) {
  return Response.json(data, {status, headers:{'Cache-Control':'no-store'}});
}

function isAllowedHost(hostname) {
  const h = hostname.toLowerCase().replace(/^www\./,'');
  if (h === 'localhost' || /^\d{1,3}(\.\d{1,3}){3}$/.test(h)) return false;
  return h.endsWith('.go.id') || h.endsWith('.co.id') || h.endsWith('.or.id') || h.endsWith('.ac.id') ||
         ['go.id','co.id','or.id','ac.id'].includes(h);
}

function rootDomain(hostname) {
  const h = hostname.toLowerCase().replace(/^www\./,'');
  const p = h.split('.');
  // Indonesia public-sector domains commonly end in go.id / co.id / or.id / ac.id.
  if (p.length >= 3 && p[p.length-1] === 'id') return p.slice(-3).join('.');
  return h;
}

function attr(tag, name) {
  const m = tag.match(new RegExp(`${name}\\s*=\\s*["']([^"']+)["']`, 'i')) ||
            tag.match(new RegExp(`${name}\\s*=\\s*([^\\s>]+)`, 'i'));
  return m ? m[1] : '';
}

function absolute(href, base) {
  if (!href || /^(data:|javascript:|#)/i.test(href)) return null;
  try { return new URL(href, base).href; } catch { return null; }
}

function extractLogoCandidates(html, base) {
  const out = [];
  const push = v => { const u = absolute(v, base); if (u && !out.includes(u)) out.push(u); };

  // Header/logo images are usually the closest match to the institution's actual logo.
  for (const m of html.matchAll(/<img\b[^>]*>/gi)) {
    const tag = m[0];
    const src = attr(tag,'src') || attr(tag,'data-src') || attr(tag,'data-lazy-src');
    const clue = `${src} ${attr(tag,'alt')} ${attr(tag,'class')} ${attr(tag,'id')}`.toLowerCase();
    if (src && /(logo|brand|lambang|emblem|identity|header-logo|navbar-brand)/i.test(clue)) push(src);
    if (out.length >= 10) break;
  }

  // High-resolution site icons.
  for (const m of html.matchAll(/<link\b[^>]*>/gi)) {
    const tag = m[0];
    const rel = attr(tag,'rel').toLowerCase();
    if (/(apple-touch-icon|icon|shortcut icon|mask-icon)/.test(rel)) push(attr(tag,'href'));
  }

  // Social image is a useful fallback for sites whose header is generated by JavaScript.
  for (const m of html.matchAll(/<meta\b[^>]*>/gi)) {
    const tag = m[0];
    const key = (attr(tag,'property') || attr(tag,'name')).toLowerCase();
    if (['og:image','twitter:image','twitter:image:src'].includes(key)) push(attr(tag,'content'));
  }
  return out;
}

async function fetchWithTimeout(url, options={}, ms=7000) {
  const controller = new AbortController();
  const timer = setTimeout(() => controller.abort(), ms);
  try {
    return await fetch(url, {...options, signal:controller.signal, redirect:'follow'});
  } finally { clearTimeout(timer); }
}

async function fetchImage(url) {
  try {
    const r = await fetchWithTimeout(url, {
      headers:{'User-Agent':UA,'Accept':'image/avif,image/webp,image/apng,image/svg+xml,image/*,*/*;q=0.8'}
    }, 6000);
    if (!r.ok) return null;
    const type = (r.headers.get('content-type') || '').split(';')[0].trim().toLowerCase();
    const buf = await r.arrayBuffer();
    if (!buf.byteLength || buf.byteLength > 3_000_000) return null;
    const looksImage = type.startsWith('image/') || /\.(png|jpe?g|gif|webp|svg|ico)(\?|$)/i.test(url);
    if (!looksImage) return null;
    return {buf, type: type.startsWith('image/') ? type : 'image/png'};
  } catch { return null; }
}

async function resolveFromSite(siteUrl) {
  const u = new URL(siteUrl);
  const root = rootDomain(u.hostname);
  const sites = [...new Set([u.origin + '/', `https://${root}/`, `https://www.${root}/`])];

  const candidates = [];
  for (const site of sites) {
    try {
      const r = await fetchWithTimeout(site, {headers:{'User-Agent':UA,'Accept':'text/html,application/xhtml+xml'}}, 7000);
      if (!r.ok) continue;
      const type = (r.headers.get('content-type') || '').toLowerCase();
      if (!type.includes('text/html') && !type.includes('application/xhtml')) continue;
      const html = (await r.text()).slice(0, 900_000);
      candidates.push(...extractLogoCandidates(html, r.url || site));
    } catch {}
  }

  // Common conventional locations after metadata/header discovery.
  for (const origin of sites) {
    try {
      const o = new URL(origin).origin;
      candidates.push(`${o}/favicon.ico`, `${o}/favicon.png`, `${o}/apple-touch-icon.png`, `${o}/logo.png`, `${o}/images/logo.png`, `${o}/assets/images/logo.png`);
    } catch {}
  }

  // Favicon aggregators are last-resort network sources.
  candidates.push(
    `https://www.google.com/s2/favicons?sz=256&domain_url=${encodeURIComponent(`https://${root}`)}`,
    `https://icons.duckduckgo.com/ip3/${encodeURIComponent(root)}.ico`
  );

  for (const c of [...new Set(candidates)].slice(0, 30)) {
    const image = await fetchImage(c);
    if (image) return image;
  }
  return null;
}

export async function GET(request) {
  const reqUrl = new URL(request.url);
  const target = reqUrl.searchParams.get('url') || '';
  const name = reqUrl.searchParams.get('name') || 'RI';

  let u;
  try { u = new URL(target); } catch {
    return new Response(svgFallback(name), {status:200, headers:{'Content-Type':'image/svg+xml; charset=utf-8','Cache-Control':'public, max-age=3600'}});
  }
  if (!['http:','https:'].includes(u.protocol) || !isAllowedHost(u.hostname)) {
    return new Response(svgFallback(name), {status:200, headers:{'Content-Type':'image/svg+xml; charset=utf-8','Cache-Control':'public, max-age=3600'}});
  }

  const image = await resolveFromSite(u.href);
  if (image) {
    return new Response(image.buf, {
      status:200,
      headers:{
        'Content-Type':image.type,
        'Cache-Control':'public, s-maxage=86400, stale-while-revalidate=604800',
        'Access-Control-Allow-Origin':'*'
      }
    });
  }
  return new Response(svgFallback(name), {
    status:200,
    headers:{'Content-Type':'image/svg+xml; charset=utf-8','Cache-Control':'public, s-maxage=3600','Access-Control-Allow-Origin':'*'}
  });
}
